#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-05-02"

[env.prod]
name = "referee-fyi-share"
compatibility_date = "2024-05-02"
main = "./src/index.ts"
kv_namespaces = [
    { binding = "SHARES", id = "667b3f219f284aa7b4a88d37044ae9d9" },
    { binding = "INVITATIONS", id = "bf2c971507354390ba314b8e18b4e908" },
    { binding = "USERS", id = "5af999adc77a401880ed7339dd3c02c2" },
    { binding = "REQUEST_CODES", id = "8aff2d84d528425689cd1d110053313f" },
    { binding = "SYSTEM_KEYS", id = "57ca4e6108bb4f3a8ac1a069d68aaae8" },
    { binding = "ASSETS", id = "b7df12c587e3445d823e33fc1a4a213e" },
]
routes = [
    { pattern = "share.referee.fyi", custom_domain = true },
    { pattern = "referee.fyi/api/*", zone_name = "referee.fyi" },
]
logpush = true
tail_consumers = [{ service = "referee-fyi-share-tail" }]

[env.prod.vars]
CLOUDFLARE_EMAIL = "brendan@bren.app"
CLOUDFLARE_IMAGES_ACCOUNT_ID = "f9b9e088206092e25d77f0def608c799"

[env.staging]
name = "referee-fyi-share-staging"
compatibility_date = "2024-05-02"
main = "./src/index.ts"
kv_namespaces = [
    { binding = "SHARES", id = "667b3f219f284aa7b4a88d37044ae9d9", preview_id = "667b3f219f284aa7b4a88d37044ae9d9" },
    { binding = "INVITATIONS", id = "bf2c971507354390ba314b8e18b4e908", preview_id = "bf2c971507354390ba314b8e18b4e908" },
    { binding = "USERS", id = "5af999adc77a401880ed7339dd3c02c2", preview_id = "5af999adc77a401880ed7339dd3c02c2" },
    { binding = "REQUEST_CODES", id = "8aff2d84d528425689cd1d110053313f", preview_id = "8aff2d84d528425689cd1d110053313f" },
    { binding = "SYSTEM_KEYS", id = "57ca4e6108bb4f3a8ac1a069d68aaae8", preview_id = "57ca4e6108bb4f3a8ac1a069d68aaae8" },
    { binding = "ASSETS", id = "a0a3ad56955b4c829f6756a69ae48d39" },
]
logpush = true


[env.staging.vars]
CLOUDFLARE_EMAIL = "brendan@bren.app"
CLOUDFLARE_IMAGES_ACCOUNT_ID = "f9b9e088206092e25d77f0def608c799"

[[env.staging.durable_objects.bindings]]
name = "INCIDENTS"
class_name = "ShareInstance"

[[env.prod.durable_objects.bindings]]
name = "INCIDENTS"
class_name = "ShareInstance"

[[migrations]]
tag = "v1"
new_classes = ["EventIncidents"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "EventIncidents", to = "ShareInstance" }]
