CREATE TABLE IF NOT EXISTS flags (
  key TEXT UNIQUE PRIMARY KEY NOT NULL,
  value TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) WITHOUT ROWID;


CREATE INDEX IF NOT EXISTS idx_flags_updated_at ON flags(updated_at);
