/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StatsImport } from './routes/stats'
import { Route as SettingsImport } from './routes/settings'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as SkuRouteImport } from './routes/$sku/route'
import { Route as IndexImport } from './routes/index'
import { Route as SkuIndexImport } from './routes/$sku/index'
import { Route as SkuSummaryImport } from './routes/$sku/summary'
import { Route as SkuSkillsImport } from './routes/$sku/skills'
import { Route as SkuDevtoolsImport } from './routes/$sku/devtools'
import { Route as SkuDeletedImport } from './routes/$sku/deleted'
import { Route as SkuDivisionIndexImport } from './routes/$sku/$division/index'
import { Route as RulesProgramYearImport } from './routes/rules/$program/$year'
import { Route as SkuTeamTeamImport } from './routes/$sku/team/$team'

// Create/Update Routes

const StatsRoute = StatsImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const SkuRouteRoute = SkuRouteImport.update({
  id: '/$sku',
  path: '/$sku',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SkuIndexRoute = SkuIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkuRouteRoute,
} as any)

const SkuSummaryRoute = SkuSummaryImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => SkuRouteRoute,
} as any)

const SkuSkillsRoute = SkuSkillsImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SkuRouteRoute,
} as any)

const SkuDevtoolsRoute = SkuDevtoolsImport.update({
  id: '/devtools',
  path: '/devtools',
  getParentRoute: () => SkuRouteRoute,
} as any)

const SkuDeletedRoute = SkuDeletedImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => SkuRouteRoute,
} as any)

const SkuDivisionIndexRoute = SkuDivisionIndexImport.update({
  id: '/$division/',
  path: '/$division/',
  getParentRoute: () => SkuRouteRoute,
} as any)

const RulesProgramYearRoute = RulesProgramYearImport.update({
  id: '/rules/$program/$year',
  path: '/rules/$program/$year',
  getParentRoute: () => rootRoute,
} as any)

const SkuTeamTeamRoute = SkuTeamTeamImport.update({
  id: '/team/$team',
  path: '/team/$team',
  getParentRoute: () => SkuRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$sku': {
      id: '/$sku'
      path: '/$sku'
      fullPath: '/$sku'
      preLoaderRoute: typeof SkuRouteImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsImport
      parentRoute: typeof rootRoute
    }
    '/$sku/deleted': {
      id: '/$sku/deleted'
      path: '/deleted'
      fullPath: '/$sku/deleted'
      preLoaderRoute: typeof SkuDeletedImport
      parentRoute: typeof SkuRouteImport
    }
    '/$sku/devtools': {
      id: '/$sku/devtools'
      path: '/devtools'
      fullPath: '/$sku/devtools'
      preLoaderRoute: typeof SkuDevtoolsImport
      parentRoute: typeof SkuRouteImport
    }
    '/$sku/skills': {
      id: '/$sku/skills'
      path: '/skills'
      fullPath: '/$sku/skills'
      preLoaderRoute: typeof SkuSkillsImport
      parentRoute: typeof SkuRouteImport
    }
    '/$sku/summary': {
      id: '/$sku/summary'
      path: '/summary'
      fullPath: '/$sku/summary'
      preLoaderRoute: typeof SkuSummaryImport
      parentRoute: typeof SkuRouteImport
    }
    '/$sku/': {
      id: '/$sku/'
      path: '/'
      fullPath: '/$sku/'
      preLoaderRoute: typeof SkuIndexImport
      parentRoute: typeof SkuRouteImport
    }
    '/$sku/team/$team': {
      id: '/$sku/team/$team'
      path: '/team/$team'
      fullPath: '/$sku/team/$team'
      preLoaderRoute: typeof SkuTeamTeamImport
      parentRoute: typeof SkuRouteImport
    }
    '/rules/$program/$year': {
      id: '/rules/$program/$year'
      path: '/rules/$program/$year'
      fullPath: '/rules/$program/$year'
      preLoaderRoute: typeof RulesProgramYearImport
      parentRoute: typeof rootRoute
    }
    '/$sku/$division/': {
      id: '/$sku/$division/'
      path: '/$division'
      fullPath: '/$sku/$division'
      preLoaderRoute: typeof SkuDivisionIndexImport
      parentRoute: typeof SkuRouteImport
    }
  }
}

// Create and export the route tree

interface SkuRouteRouteChildren {
  SkuDeletedRoute: typeof SkuDeletedRoute
  SkuDevtoolsRoute: typeof SkuDevtoolsRoute
  SkuSkillsRoute: typeof SkuSkillsRoute
  SkuSummaryRoute: typeof SkuSummaryRoute
  SkuIndexRoute: typeof SkuIndexRoute
  SkuTeamTeamRoute: typeof SkuTeamTeamRoute
  SkuDivisionIndexRoute: typeof SkuDivisionIndexRoute
}

const SkuRouteRouteChildren: SkuRouteRouteChildren = {
  SkuDeletedRoute: SkuDeletedRoute,
  SkuDevtoolsRoute: SkuDevtoolsRoute,
  SkuSkillsRoute: SkuSkillsRoute,
  SkuSummaryRoute: SkuSummaryRoute,
  SkuIndexRoute: SkuIndexRoute,
  SkuTeamTeamRoute: SkuTeamTeamRoute,
  SkuDivisionIndexRoute: SkuDivisionIndexRoute,
}

const SkuRouteRouteWithChildren = SkuRouteRoute._addFileChildren(
  SkuRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$sku': typeof SkuRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku/': typeof SkuIndexRoute
  '/$sku/team/$team': typeof SkuTeamTeamRoute
  '/rules/$program/$year': typeof RulesProgramYearRoute
  '/$sku/$division': typeof SkuDivisionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku': typeof SkuIndexRoute
  '/$sku/team/$team': typeof SkuTeamTeamRoute
  '/rules/$program/$year': typeof RulesProgramYearRoute
  '/$sku/$division': typeof SkuDivisionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$sku': typeof SkuRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku/': typeof SkuIndexRoute
  '/$sku/team/$team': typeof SkuTeamTeamRoute
  '/rules/$program/$year': typeof RulesProgramYearRoute
  '/$sku/$division/': typeof SkuDivisionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$sku'
    | '/privacy'
    | '/settings'
    | '/stats'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku/'
    | '/$sku/team/$team'
    | '/rules/$program/$year'
    | '/$sku/$division'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/settings'
    | '/stats'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku'
    | '/$sku/team/$team'
    | '/rules/$program/$year'
    | '/$sku/$division'
  id:
    | '__root__'
    | '/'
    | '/$sku'
    | '/privacy'
    | '/settings'
    | '/stats'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku/'
    | '/$sku/team/$team'
    | '/rules/$program/$year'
    | '/$sku/$division/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkuRouteRoute: typeof SkuRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  RulesProgramYearRoute: typeof RulesProgramYearRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkuRouteRoute: SkuRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  RulesProgramYearRoute: RulesProgramYearRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$sku",
        "/privacy",
        "/settings",
        "/stats",
        "/rules/$program/$year"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$sku": {
      "filePath": "$sku/route.tsx",
      "children": [
        "/$sku/deleted",
        "/$sku/devtools",
        "/$sku/skills",
        "/$sku/summary",
        "/$sku/",
        "/$sku/team/$team",
        "/$sku/$division/"
      ]
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/stats": {
      "filePath": "stats.tsx"
    },
    "/$sku/deleted": {
      "filePath": "$sku/deleted.tsx",
      "parent": "/$sku"
    },
    "/$sku/devtools": {
      "filePath": "$sku/devtools.tsx",
      "parent": "/$sku"
    },
    "/$sku/skills": {
      "filePath": "$sku/skills.tsx",
      "parent": "/$sku"
    },
    "/$sku/summary": {
      "filePath": "$sku/summary.tsx",
      "parent": "/$sku"
    },
    "/$sku/": {
      "filePath": "$sku/index.tsx",
      "parent": "/$sku"
    },
    "/$sku/team/$team": {
      "filePath": "$sku/team/$team.tsx",
      "parent": "/$sku"
    },
    "/rules/$program/$year": {
      "filePath": "rules/$program/$year.tsx"
    },
    "/$sku/$division/": {
      "filePath": "$sku/$division/index.tsx",
      "parent": "/$sku"
    }
  }
}
ROUTE_MANIFEST_END */
