/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as IndexImport } from './routes/index'
import { Route as SkuIndexImport } from './routes/$sku/index'
import { Route as SkuTeamImport } from './routes/$sku/team'
import { Route as SkuSummaryImport } from './routes/$sku/summary'
import { Route as SkuSkillsImport } from './routes/$sku/skills'
import { Route as SkuDivisionImport } from './routes/$sku/division'
import { Route as SkuDevtoolsImport } from './routes/$sku/devtools'
import { Route as SkuDeletedImport } from './routes/$sku/deleted'
import { Route as SkuHomeIndexImport } from './routes/$sku/home/index'
import { Route as SkuHomeTeamsImport } from './routes/$sku/home/teams'
import { Route as SkuHomeMatchesImport } from './routes/$sku/home/matches'
import { Route as SkuHomeManageImport } from './routes/$sku/home/manage'
import { Route as SkuDialogsTeamImport } from './routes/$sku/dialogs/team'
import { Route as SkuDialogsNewImport } from './routes/$sku/dialogs/new'
import { Route as SkuDialogsMatchImport } from './routes/$sku/dialogs/match'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SkuIndexRoute = SkuIndexImport.update({
  id: '/$sku/',
  path: '/$sku/',
  getParentRoute: () => rootRoute,
} as any)

const SkuTeamRoute = SkuTeamImport.update({
  id: '/$sku/team',
  path: '/$sku/team',
  getParentRoute: () => rootRoute,
} as any)

const SkuSummaryRoute = SkuSummaryImport.update({
  id: '/$sku/summary',
  path: '/$sku/summary',
  getParentRoute: () => rootRoute,
} as any)

const SkuSkillsRoute = SkuSkillsImport.update({
  id: '/$sku/skills',
  path: '/$sku/skills',
  getParentRoute: () => rootRoute,
} as any)

const SkuDivisionRoute = SkuDivisionImport.update({
  id: '/$sku/division',
  path: '/$sku/division',
  getParentRoute: () => rootRoute,
} as any)

const SkuDevtoolsRoute = SkuDevtoolsImport.update({
  id: '/$sku/devtools',
  path: '/$sku/devtools',
  getParentRoute: () => rootRoute,
} as any)

const SkuDeletedRoute = SkuDeletedImport.update({
  id: '/$sku/deleted',
  path: '/$sku/deleted',
  getParentRoute: () => rootRoute,
} as any)

const SkuHomeIndexRoute = SkuHomeIndexImport.update({
  id: '/$sku/home/',
  path: '/$sku/home/',
  getParentRoute: () => rootRoute,
} as any)

const SkuHomeTeamsRoute = SkuHomeTeamsImport.update({
  id: '/$sku/home/teams',
  path: '/$sku/home/teams',
  getParentRoute: () => rootRoute,
} as any)

const SkuHomeMatchesRoute = SkuHomeMatchesImport.update({
  id: '/$sku/home/matches',
  path: '/$sku/home/matches',
  getParentRoute: () => rootRoute,
} as any)

const SkuHomeManageRoute = SkuHomeManageImport.update({
  id: '/$sku/home/manage',
  path: '/$sku/home/manage',
  getParentRoute: () => rootRoute,
} as any)

const SkuDialogsTeamRoute = SkuDialogsTeamImport.update({
  id: '/$sku/dialogs/team',
  path: '/$sku/dialogs/team',
  getParentRoute: () => rootRoute,
} as any)

const SkuDialogsNewRoute = SkuDialogsNewImport.update({
  id: '/$sku/dialogs/new',
  path: '/$sku/dialogs/new',
  getParentRoute: () => rootRoute,
} as any)

const SkuDialogsMatchRoute = SkuDialogsMatchImport.update({
  id: '/$sku/dialogs/match',
  path: '/$sku/dialogs/match',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/$sku/deleted': {
      id: '/$sku/deleted'
      path: '/$sku/deleted'
      fullPath: '/$sku/deleted'
      preLoaderRoute: typeof SkuDeletedImport
      parentRoute: typeof rootRoute
    }
    '/$sku/devtools': {
      id: '/$sku/devtools'
      path: '/$sku/devtools'
      fullPath: '/$sku/devtools'
      preLoaderRoute: typeof SkuDevtoolsImport
      parentRoute: typeof rootRoute
    }
    '/$sku/division': {
      id: '/$sku/division'
      path: '/$sku/division'
      fullPath: '/$sku/division'
      preLoaderRoute: typeof SkuDivisionImport
      parentRoute: typeof rootRoute
    }
    '/$sku/skills': {
      id: '/$sku/skills'
      path: '/$sku/skills'
      fullPath: '/$sku/skills'
      preLoaderRoute: typeof SkuSkillsImport
      parentRoute: typeof rootRoute
    }
    '/$sku/summary': {
      id: '/$sku/summary'
      path: '/$sku/summary'
      fullPath: '/$sku/summary'
      preLoaderRoute: typeof SkuSummaryImport
      parentRoute: typeof rootRoute
    }
    '/$sku/team': {
      id: '/$sku/team'
      path: '/$sku/team'
      fullPath: '/$sku/team'
      preLoaderRoute: typeof SkuTeamImport
      parentRoute: typeof rootRoute
    }
    '/$sku/': {
      id: '/$sku/'
      path: '/$sku'
      fullPath: '/$sku'
      preLoaderRoute: typeof SkuIndexImport
      parentRoute: typeof rootRoute
    }
    '/$sku/dialogs/match': {
      id: '/$sku/dialogs/match'
      path: '/$sku/dialogs/match'
      fullPath: '/$sku/dialogs/match'
      preLoaderRoute: typeof SkuDialogsMatchImport
      parentRoute: typeof rootRoute
    }
    '/$sku/dialogs/new': {
      id: '/$sku/dialogs/new'
      path: '/$sku/dialogs/new'
      fullPath: '/$sku/dialogs/new'
      preLoaderRoute: typeof SkuDialogsNewImport
      parentRoute: typeof rootRoute
    }
    '/$sku/dialogs/team': {
      id: '/$sku/dialogs/team'
      path: '/$sku/dialogs/team'
      fullPath: '/$sku/dialogs/team'
      preLoaderRoute: typeof SkuDialogsTeamImport
      parentRoute: typeof rootRoute
    }
    '/$sku/home/manage': {
      id: '/$sku/home/manage'
      path: '/$sku/home/manage'
      fullPath: '/$sku/home/manage'
      preLoaderRoute: typeof SkuHomeManageImport
      parentRoute: typeof rootRoute
    }
    '/$sku/home/matches': {
      id: '/$sku/home/matches'
      path: '/$sku/home/matches'
      fullPath: '/$sku/home/matches'
      preLoaderRoute: typeof SkuHomeMatchesImport
      parentRoute: typeof rootRoute
    }
    '/$sku/home/teams': {
      id: '/$sku/home/teams'
      path: '/$sku/home/teams'
      fullPath: '/$sku/home/teams'
      preLoaderRoute: typeof SkuHomeTeamsImport
      parentRoute: typeof rootRoute
    }
    '/$sku/home/': {
      id: '/$sku/home/'
      path: '/$sku/home'
      fullPath: '/$sku/home'
      preLoaderRoute: typeof SkuHomeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/division': typeof SkuDivisionRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku/team': typeof SkuTeamRoute
  '/$sku': typeof SkuIndexRoute
  '/$sku/dialogs/match': typeof SkuDialogsMatchRoute
  '/$sku/dialogs/new': typeof SkuDialogsNewRoute
  '/$sku/dialogs/team': typeof SkuDialogsTeamRoute
  '/$sku/home/manage': typeof SkuHomeManageRoute
  '/$sku/home/matches': typeof SkuHomeMatchesRoute
  '/$sku/home/teams': typeof SkuHomeTeamsRoute
  '/$sku/home': typeof SkuHomeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/division': typeof SkuDivisionRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku/team': typeof SkuTeamRoute
  '/$sku': typeof SkuIndexRoute
  '/$sku/dialogs/match': typeof SkuDialogsMatchRoute
  '/$sku/dialogs/new': typeof SkuDialogsNewRoute
  '/$sku/dialogs/team': typeof SkuDialogsTeamRoute
  '/$sku/home/manage': typeof SkuHomeManageRoute
  '/$sku/home/matches': typeof SkuHomeMatchesRoute
  '/$sku/home/teams': typeof SkuHomeTeamsRoute
  '/$sku/home': typeof SkuHomeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/$sku/deleted': typeof SkuDeletedRoute
  '/$sku/devtools': typeof SkuDevtoolsRoute
  '/$sku/division': typeof SkuDivisionRoute
  '/$sku/skills': typeof SkuSkillsRoute
  '/$sku/summary': typeof SkuSummaryRoute
  '/$sku/team': typeof SkuTeamRoute
  '/$sku/': typeof SkuIndexRoute
  '/$sku/dialogs/match': typeof SkuDialogsMatchRoute
  '/$sku/dialogs/new': typeof SkuDialogsNewRoute
  '/$sku/dialogs/team': typeof SkuDialogsTeamRoute
  '/$sku/home/manage': typeof SkuHomeManageRoute
  '/$sku/home/matches': typeof SkuHomeMatchesRoute
  '/$sku/home/teams': typeof SkuHomeTeamsRoute
  '/$sku/home/': typeof SkuHomeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/settings'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/division'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku/team'
    | '/$sku'
    | '/$sku/dialogs/match'
    | '/$sku/dialogs/new'
    | '/$sku/dialogs/team'
    | '/$sku/home/manage'
    | '/$sku/home/matches'
    | '/$sku/home/teams'
    | '/$sku/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/settings'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/division'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku/team'
    | '/$sku'
    | '/$sku/dialogs/match'
    | '/$sku/dialogs/new'
    | '/$sku/dialogs/team'
    | '/$sku/home/manage'
    | '/$sku/home/matches'
    | '/$sku/home/teams'
    | '/$sku/home'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/settings'
    | '/$sku/deleted'
    | '/$sku/devtools'
    | '/$sku/division'
    | '/$sku/skills'
    | '/$sku/summary'
    | '/$sku/team'
    | '/$sku/'
    | '/$sku/dialogs/match'
    | '/$sku/dialogs/new'
    | '/$sku/dialogs/team'
    | '/$sku/home/manage'
    | '/$sku/home/matches'
    | '/$sku/home/teams'
    | '/$sku/home/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SkuDeletedRoute: typeof SkuDeletedRoute
  SkuDevtoolsRoute: typeof SkuDevtoolsRoute
  SkuDivisionRoute: typeof SkuDivisionRoute
  SkuSkillsRoute: typeof SkuSkillsRoute
  SkuSummaryRoute: typeof SkuSummaryRoute
  SkuTeamRoute: typeof SkuTeamRoute
  SkuIndexRoute: typeof SkuIndexRoute
  SkuDialogsMatchRoute: typeof SkuDialogsMatchRoute
  SkuDialogsNewRoute: typeof SkuDialogsNewRoute
  SkuDialogsTeamRoute: typeof SkuDialogsTeamRoute
  SkuHomeManageRoute: typeof SkuHomeManageRoute
  SkuHomeMatchesRoute: typeof SkuHomeMatchesRoute
  SkuHomeTeamsRoute: typeof SkuHomeTeamsRoute
  SkuHomeIndexRoute: typeof SkuHomeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SkuDeletedRoute: SkuDeletedRoute,
  SkuDevtoolsRoute: SkuDevtoolsRoute,
  SkuDivisionRoute: SkuDivisionRoute,
  SkuSkillsRoute: SkuSkillsRoute,
  SkuSummaryRoute: SkuSummaryRoute,
  SkuTeamRoute: SkuTeamRoute,
  SkuIndexRoute: SkuIndexRoute,
  SkuDialogsMatchRoute: SkuDialogsMatchRoute,
  SkuDialogsNewRoute: SkuDialogsNewRoute,
  SkuDialogsTeamRoute: SkuDialogsTeamRoute,
  SkuHomeManageRoute: SkuHomeManageRoute,
  SkuHomeMatchesRoute: SkuHomeMatchesRoute,
  SkuHomeTeamsRoute: SkuHomeTeamsRoute,
  SkuHomeIndexRoute: SkuHomeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/privacy",
        "/settings",
        "/$sku/deleted",
        "/$sku/devtools",
        "/$sku/division",
        "/$sku/skills",
        "/$sku/summary",
        "/$sku/team",
        "/$sku/",
        "/$sku/dialogs/match",
        "/$sku/dialogs/new",
        "/$sku/dialogs/team",
        "/$sku/home/manage",
        "/$sku/home/matches",
        "/$sku/home/teams",
        "/$sku/home/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/$sku/deleted": {
      "filePath": "$sku/deleted.tsx"
    },
    "/$sku/devtools": {
      "filePath": "$sku/devtools.tsx"
    },
    "/$sku/division": {
      "filePath": "$sku/division.tsx"
    },
    "/$sku/skills": {
      "filePath": "$sku/skills.tsx"
    },
    "/$sku/summary": {
      "filePath": "$sku/summary.tsx"
    },
    "/$sku/team": {
      "filePath": "$sku/team.tsx"
    },
    "/$sku/": {
      "filePath": "$sku/index.tsx"
    },
    "/$sku/dialogs/match": {
      "filePath": "$sku/dialogs/match.tsx"
    },
    "/$sku/dialogs/new": {
      "filePath": "$sku/dialogs/new.tsx"
    },
    "/$sku/dialogs/team": {
      "filePath": "$sku/dialogs/team.tsx"
    },
    "/$sku/home/manage": {
      "filePath": "$sku/home/manage.tsx"
    },
    "/$sku/home/matches": {
      "filePath": "$sku/home/matches.tsx"
    },
    "/$sku/home/teams": {
      "filePath": "$sku/home/teams.tsx"
    },
    "/$sku/home/": {
      "filePath": "$sku/home/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
