name: Staging Build

on:
  push:
    branches-ignore:
      - main

jobs:
  test-lib:
    runs-on: ubuntu-latest
    name: Test Library
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run test
        working-directory: "lib/consistency"
      - run: npm run test
        working-directory: "lib/pdf"
      - run: npm run test
        working-directory: "lib/share"
  deploy:
    needs: test-lib
    runs-on: ubuntu-latest
    name: Deploy Staging
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run worker:build
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "worker/sync"
          environment: "staging"
