name: Deploy Staging

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Staging
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run build
      - run: npm run frontend:build
      - name: Preview Alias
        id: preview_alias
        run: |
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          SAFE_REF=$(echo "${GITHUB_REF_NAME}" | sed 's|/|-|g' | sed 's|[^a-zA-Z0-9._-]||g')
          echo "SAFE_REF=$SAFE_REF"
          WORKER=$(cat ./wrangler.jsonc | jq -r ".name")
          echo "WORKER=$WORKER"
          URL="https://${SAFE_REF}-${WORKER}.bren.workers.dev"
          echo "URL=$URL"
          echo "preview_alias=$SAFE_REF" >> $GITHUB_OUTPUT
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: versions upload --preview-alias ${{ steps.preview_alias.outputs.preview_alias }}
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "worker/sync"
          environment: "staging"
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "worker/rules-indexer"
          environment: "staging"
